# Reference: https://github.com/mrgnlabs/anchor-test-action/blob/main/action.yaml
name: "Run Anchor Test for Solana Programs"
author: "Seabed Labs"
description: "Run anchor tests"
branding:
  icon: anchor
  color: blue
inputs:
  args:
    description: "anchor test arguments"
    required: false
    default: ""
  workspace_dir:
    description: "anchor workspace directory"
    required: false
    default: "."
runs:
  using: "docker"
  image: "docker://seabedlabs/solana-dev-env:rust-v1.72.0-v1.16.13_anchor-v0.28.0_node-v18.17.1"
  entrypoint: shell-exec
  args:
    - "cd ${{ inputs.workspace_dir }}"
    - yarn install --ignore-scripts
    - "solana-keygen new --no-bip39-passphrase"
    - "anchor test ${{ inputs.args }}"
